### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Havret**
Hi Sacha,

Thank you for your great work! I really love the idea which you presented here https://sachabarbs.wordpress.com/2018/05/22/akka-net-di-testing-considerations/ and I decided to take you solution a little further. :)

The initial plan was to get rid of the container from my unit tests, simplify their setup, and remove the necessity to register my child actors twice. First time in the instance of IChildActorCreator and the second during container configuration. I hope you like. 

Cheers and happy holidays. :)

### CODE REVIEW

**Comment by sachabarber** [comment]
I'm on holiday right now but I'll review this PR when I'm back

Hopefully I agree and I'll merge it in

**Review by sachabarber — COMMENTED** [review]
Whilst I'm still on holiday, I've had a look at this for a bit


And to be honest for me some of what you have added makes sense but I would still want to use the IOC container (or at least be able to) in my tests 

I like some of the changes but others I would prefer what I have,so what may make more sense this time is for you to perhaps fork this repo and then apply your PR to your own fork 

Honestly don't mean to be an ass or anything,  I think we are just trying to do slightly different things. 


But thanks for the kind comments, and taking the time to create the PR

Like I say I think we just want slightly different things, and since I'm probably going to need this again I would prefer my mental model of what's in this repo to be how I remember it

Hope you understand that 

But as I say nothing to stop you forking to your own repo

**Comment by Havret** [comment]
Thanks for reply. :) If you don't merge it I really don't mind. Enforcing anything is the last thing I want. 

The only reason I made this PR was to show how I evolved my solution from what was in your blog post, and I think this was the easiest way to do it. 

I removed container just to make a point that you don't need it to set up your test suits. It can easily be restored if that suits your needs. My main goal was to simplify creation of child actors and to change the way how you register them. It was strange to me that in your solution you have to do it twice.

**Comment by sachabarber** [comment]
Ah but I don't do it twice the one in the child creator is like a factory the resolves from container first time after that it's like a memoised factory 

So while I see your point, I also see my point

**Comment by Havret** [comment]
To make everything up and running you have to physically make _registration_ here:

https://github.com/sachabarber/AkkaNetDITesting/blob/22cc4ecad1826a179457879253bca2b1e099c331/AkkaDITest/AkkaDITest/Actors/ChildActorCreator.cs#L24

and here:

https://github.com/sachabarber/AkkaNetDITesting/blob/22cc4ecad1826a179457879253bca2b1e099c331/AkkaDITest/AkkaDITest/IOC/GlobalAutofacModule.cs#L26

Otherwise, it will fail at runtime. Every time you want to add sth new to your ChildActorCreator you have to add it in two places. Thus, if manual intervention is required in two areas it is highly probable that you will forget about it from time to time. And then, yes... it will blow.

Of course, you can make registration by convention with your IoC container, and that also should do the trick, and decrease the number of total registrations but that's not my point.

Ok. I ran out of arguments. Sorry for keeping your distracted by these PR answers. That was the very last one. Enjoy your holidays!

**Comment by sachabarber** [comment]
Yeah I see where you are coming from, let me have a proper look when I get back

I may just take some of the code and not whole PR

But honestly thanks for the interest in this repo

**Comment by sachabarber** [comment]
So I've had another look

I've argued myself back again. Argggghhhh, at 5:29am on hols too

Here's my thinking 

1. I want to return Props not IActorRef so it can be reused to create same memoised props

2. By using Props I am open to using Akka built in supervisors, that work with Props not IActorRef 

3. I think (so does Akka I think)  it should be illegal to have 2 actors of same name,so by you allowing null for name you're kind of allowing that

3.by using IActorRef (which really you should only get by selection or direct handle, like Sender etc etc) you are not really buying into Akka lifecycle, which is why I used props

I do agree with fact that perhaps some sort of convention registration would be good

But I like my reusable Props factory (which is always safe to be reused as its not a pointer to a specific actor (yours is) but rather a way to create an actor)

I think what you have done may suit your usecase 

My stuff came out if frustration trying to do integration testing for portions of my actor trees

So I still wanted to use the IOC container too

I think your setup is great for unit tests

Anyway I think that's my final thoughts

**Comment by Havret** [comment]
I think I have addressed all your concerns in the recent update. :)

Ad. 1. You are not creating props, container does it in your behalf. And they are not memoised in any way, unless you do so (there is not a thing in current implementation. 

Ad. 2. I think I addressed it in e7d946e 

Ad. 3. Yes it is illegal, you cannot have two Actors with the same name. But if you pass null instead of explicitly setting actor's name, Akka will do it for you and pick some unique name. What I did was just following the Akka API:

```    
public abstract IActorRef ActorOf(Props props, string name = null);
```

**Comment by sachabarber** [comment]
Current  implementation definitely memorize, via the use of dictionary string/function, but honestly it s minor issue on I'll merge this

**Pull request merged**
